# Generated by Django 6.0.4 on 2026-05-10 09:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of author')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type of genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title of book')),
                ('summery', models.CharField(max_length=1500, verbose_name='Annotation')),
                ('imprint', models.CharField(blank=True, max_length=100, verbose_name='Publishing House')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('authors', models.ManyToManyField(to='store.author', verbose_name='Authors')),
                ('genre', models.ManyToManyField(to='store.genre', verbose_name='Genres')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.language', verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique id of this book', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200, verbose_name='Stamp of the publishing house')),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='Possible return date')),
                ('status', models.CharField(blank=True, choices=[('r', 'reserved'), ('m', 'maintenance'), ('s', 'sold'), ('a', 'available')], default='m', max_length=1, verbose_name='Status')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='store.book', verbose_name='Book')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be +375(XX)XXX-XX-XX.', regex='^\\+375\\((25|29|33|44)\\)\\d{3}\\-\\d{2}-\\d{2}$')], verbose_name='Phone number')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18, message='User must be older then 18')], verbose_name='Age')),
                ('address', models.TextField(blank=True, verbose_name='Delivery address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of order')),
                ('status', models.CharField(choices=[('c', 'Cancel'), ('d', 'Done'), ('n', 'New'), ('p', 'In process')], default='n', max_length=1, verbose_name='Status of order')),
                ('books', models.ManyToManyField(to='store.book', verbose_name='Books in order')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.client', verbose_name='Client')),
            ],
        ),
    ]
