# Generated by Django 6.0.4 on 2026-05-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price of book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'maintenance'), ('a', 'available'), ('s', 'sold'), ('r', 'reserved')], default='m', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('c', 'Cancel'), ('p', 'In process'), ('d', 'Done')], default='n', max_length=1, verbose_name='Status of order'),
        ),
    ]
