# Generated by Django 6.0.4 on 2026-05-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_bookinstance_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Book cover'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'reserved'), ('m', 'maintenance'), ('a', 'available'), ('s', 'sold')], default='m', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'In process'), ('d', 'Done'), ('n', 'New'), ('c', 'Cancel')], default='n', max_length=1, verbose_name='Status of order'),
        ),
    ]
