# Generated by Django 6.0.4 on 2026-05-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_book_cover_alter_bookinstance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'available'), ('m', 'maintenance'), ('s', 'sold'), ('r', 'reserved')], default='m', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('c', 'Cancel'), ('d', 'Done'), ('n', 'New'), ('p', 'In process')], default='n', max_length=1, verbose_name='Status of order'),
        ),
    ]
