# Generated by Django 6.0.4 on 2026-05-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_bookinstance_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summery',
            field=models.TextField(verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('s', 'sold'), ('m', 'maintenance'), ('r', 'reserved'), ('a', 'available')], default='m', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('p', 'In process'), ('d', 'Done'), ('c', 'Cancel')], default='n', max_length=1, verbose_name='Status of order'),
        ),
    ]
