# Generated by Django 6.0.4 on 2026-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_book_summery_alter_bookinstance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'available'), ('s', 'sold'), ('m', 'maintenance'), ('r', 'reserved')], default='m', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('d', 'Done'), ('n', 'New'), ('p', 'In process'), ('c', 'Cancel')], default='n', max_length=1, verbose_name='Status of order'),
        ),
    ]
