# Generated by Django 6.0.4 on 2026-05-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_bookinstance_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'maintenance'), ('r', 'reserved'), ('s', 'sold'), ('a', 'available')], default='m', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('c', 'Cancel'), ('p', 'In process'), ('d', 'Done'), ('n', 'New')], default='n', max_length=1, verbose_name='Status of order'),
        ),
    ]
