# Generated by Django 6.0.4 on 2026-05-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_bookinstance_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'available'), ('r', 'reserved'), ('m', 'maintenance'), ('s', 'sold')], default='m', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'In process'), ('c', 'Cancel'), ('n', 'New'), ('d', 'Done')], default='n', max_length=1, verbose_name='Status of order'),
        ),
    ]
