# Generated by Django 6.0.4 on 2026-05-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_bookinstance_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('s', 'Pickup (Self-delivery)'), ('c', 'Courier')], default='s', max_length=1, verbose_name='Delivery method'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('s', 'sold'), ('m', 'maintenance'), ('a', 'available'), ('r', 'reserved')], default='m', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('p', 'In process'), ('d', 'Done'), ('c', 'Cancel')], default='n', max_length=1, verbose_name='Status of order'),
        ),
    ]
