# Generated by Django 6.0.4 on 2026-05-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_remove_client_age_client_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=17, verbose_name='Phone number'),
        ),
    ]
