# Generated by Django 6.0.4 on 2026-05-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_client_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waitlist',
            unique_together={('client', 'book')},
        ),
    ]
