# Generated by Django 6.0.4 on 2026-05-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_book_created_at_book_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('Minsk', 'Minsk'), ('Brest', 'Brest'), ('Grodno', 'Grodno'), ('Gomel', 'Gomel'), ('Vitebsk', 'Vitebsk'), ('Mogilev', 'Mogilev'), ('Baranovichi', 'Baranovichi'), ('Borisov', 'Borisov'), ('Pinsk', 'Pinsk'), ('Orsha', 'Orsha'), ('Mozyr', 'Mozyr'), ('Soligorsk', 'Soligorsk'), ('Lida', 'Lida'), ('Molodechno', 'Molodechno')], default='Minsk', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, verbose_name='Delivery address (Street, House, Flat)'),
        ),
    ]
