# Generated by Django 6.0.4 on 2026-09-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_pickuppoint_order_delivery_address_order_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imprint',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Publishing House'),
        ),
    ]
