# Generated by Django 6.0.4 on 2026-09-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_book_imprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Name')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='Banner')),
                ('link', models.URLField(blank=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
