# Generated by Django 6.0.4 on 2026-09-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Count'),
        ),
    ]
