# Generated by Django 6.0.4 on 2026-05-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_article_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='full_text',
            field=models.TextField(verbose_name='Text of article'),
        ),
    ]
