# Generated by Django 6.0.4 on 2026-05-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_employee_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
