# Generated by Django 6.0.4 on 2026-09-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_faq_answer_alter_vacancy_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Partner company name')),
                ('image', models.ImageField(upload_to='companies/', verbose_name='Logo of company')),
                ('link', models.URLField(blank=True, verbose_name='Link about this company')),
            ],
        ),
    ]
