# Generated by Django 6.0.4 on 2026-09-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_companypartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/logo/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='company/videos/', verbose_name='Video'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Certificate title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/certificates/', verbose_name='Certificates')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='pages.companyinfo', verbose_name='Company')),
            ],
        ),
    ]
