# Generated by Django 6.0.4 on 2026-09-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_companyinfo_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=200, verbose_name='Short summary'),
        ),
    ]
